version: "3.8"

services:
  backend:
    build:
      context: ./cards_against_humanity/cards_against_humanity_backend # Korrigiert den Kontext
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDB: "mongodb://mongadmin:12345678@mongo:27017/mydb?authSource=admin"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./cards_against_humanity/cards_against_humanity_frontend # Korrigiert den Kontext
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongadmin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
