apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: cards-against-humanity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-against-humanity
      tier: backend
  template:
    metadata:
      labels:
        app: cards-against-humanity
        tier: backend
    spec:
      containers:
        - name: backend
          image: robinsacher/cards_against_humanity_backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__MongoDB
              value: mongodb://mongo:27017/mydb
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: cards-against-humanity
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
