apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: cards-against-humanity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-against-humanity
      tier: frontend
  template:
    metadata:
      labels:
        app: cards-against-humanity
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: robinsacher/cards_against_humanity_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: cards-against-humanity
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31098
  type: NodePort
